name: Daily Content Cron

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  call-daily-content-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron/daily-content endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          VERCEL_BYPASS_SECRET: ${{ secrets.VERCEL_BYPASS_SECRET }}
        run: |
          RESPONSE=$(curl -s -w "\n%{http_code}" -X GET https://palavraviva-git-main-robertoscunha-gmailcoms-projects.vercel.app/api/cron/generate-daily-content \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "x-vercel-protection-bypass: $VERCEL_BYPASS_SECRET")
          BODY=$(echo "$RESPONSE" | head -n -1)
          STATUS=$(echo "$RESPONSE" | tail -n1)
          echo "Status: $STATUS"
          echo "Response: $BODY"
          if [ "$STATUS" -ne 200 ]; then
            echo "Error: Endpoint returned status $STATUS"
            exit 1
          fi